replicaCount: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70

ingress:
  hosts:
    - host: monitor.company.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: monitor-prod-tls
      hosts:
        - monitor.company.com

