apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-monitor-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/muhammad-adeel9290/devops-projectfirst.git
    targetRevision: main
    path: helm/devops-monitor
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
